name: Notification on PR

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: PR notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: 나는봇
        uses: "Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9"
        with:
          args: "${{ github.actor }} 님이 ${{ github.base_ref }} 브랜치로 풀 리퀘스트를 신청하였습니다다"
